azureproject/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static # new
from django.conf import settings # new

urlpatterns = [
    path('', include('drone_recon.urls')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG: # new
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

drone_recon/urls.py
from django.urls import path
from django.conf.urls.static import static # new
from django.conf import settings # new

from . import views

app_name = 'drone_recon'

urlpatterns = [
    path("", views.index, name="index"),
    path('game', views.game, name='game'),
    path('welcome', views.welcome, name='welcome'),
    path('alreadycompleted', views.alreadyCompleted, name='alreadycompleted'),
    path('attentionfailure', views.alreadyCompleted, name='attentionfailure'),
    path("consentform", views.consentform, name="consentform"),
    path("questionnaires", views.questionnaires, name="questionnaires"),
    path('token', views.token, name='token'),
    path('fishy', views.fishy, name='fishy'),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

drone_recon/models.py
from django.core.validators import MaxValueValidator, MinValueValidator
from django.db import models

# Create your models here.

class Stimulus(models.Model):
    """Model class for a stimulus. 

    Args:
        models (models.Model): Django model object class

    Returns:
        str: name of stimulus
    """
    name = models.CharField(max_length=300)
    use = models.CharField(max_length=50)
    image = models.ImageField(upload_to='images/')
    def __str__(self):
        return self.name


class Subject(models.Model):
    """Model class for a subject.

    Args:
        models (models.Model): Django model object class
    """
    #Contains user index, external identification number, where they came from
    external_ID = models.CharField(max_length=64)
    external_source = models.CharField(max_length=64)
    age = models.IntegerField(default=0)
    sex = models.CharField(max_length=20,default='')
    gender = models.CharField(max_length=100)
    education = models.CharField(max_length=20)
    is_bot = models.BooleanField(default=False)
    psych_history = models.JSONField(default=list,blank=True,null=True)


class Session(models.Model):
    """Model class for a session.

    Args:
        models (models.Model): Django model object class
    """
    #Summary details, such as length, number of stimuli seen, average performance, date, etc.
    n_trials = models.IntegerField(default=0)
    start_time = models.DateTimeField()
    end_time = models.DateTimeField()
    session_completed = models.BooleanField(default=False)
    questionnaire_completed = models.BooleanField(default=False)
    task_completed = models.BooleanField(default=False)
    total_reward = models.IntegerField(default=0)
    total_payment = models.DecimalField(max_digits=5, decimal_places=2, default=0)
    payment_issued = models.BooleanField(default=False)
    final_performance = models.DecimalField(max_digits=6, decimal_places=5, null=True)
    payment_token = models.CharField(max_length=40)
    subject = models.ForeignKey(Subject, on_delete=models.CASCADE, related_name="sessions")
    external_study_ID = models.CharField(max_length=100,default='')
    external_session_ID = models.CharField(max_length=100,default='')
    perceived_difficulty = models.CharField(max_length=10, default="")
    task = models.CharField(max_length=100, default="")
    substances = models.JSONField(default=list,blank=True,null=True)
    sleep_quality = models.IntegerField(blank=True, null=True)
    sleep_quantity = models.IntegerField(blank=True, null=True)
    passed_attention_check = models.BooleanField(default=False)
    project = models.CharField(max_length=40,default='')
    timezone = models.CharField(max_length=200,default='')
    browser = models.CharField(max_length=200,default='')
   
    
class Strategy(models.Model):
    """Model class for after-session reporting of strategies.

    Args:
        models (models.Model): Django model object class
    """
    session = models.ForeignKey(Session, on_delete=models.CASCADE, related_name='strategies')
    prompt = models.CharField(max_length=1000)
    response = models.CharField(max_length=1000)
    
    
class Recruitment(models.Model):
    """Model class for tracking subject recruitment to studies

    Args:
        models (models.Model): Django model object class
    """
    subject = models.ForeignKey(Subject, on_delete=models.CASCADE, related_name="recruitment")
    session = models.OneToOneField(Session, on_delete=models.CASCADE, null=True, related_name="recruitment")
    prolific_study_id = models.CharField(max_length=100, default="")
    time = models.DateTimeField()
    task = models.CharField(max_length=100, default="")
    notes = models.CharField(max_length=1000, default="")
    source = models.CharField(max_length=100, default="")
    accepted = models.BooleanField(null=True, default=None)
    
    
class Trial(models.Model):
    """Model class for an individual trial

    Args:
        models (models.Model): Django model object class
    """
    #All data pertinent for an individual trial
    stimulus = models.ForeignKey(Stimulus, on_delete=models.CASCADE, related_name='trials')
    session = models.ForeignKey(Session, on_delete=models.CASCADE, related_name='trials')
    correct_class = models.CharField(max_length=100, default="")
    response = models.CharField(max_length=100, default="")
    confidence = models.FloatField(default=None, blank=True, null=True)
    correct = models.BooleanField(null=True)
    rt_classification = models.IntegerField(default=None,null=True)
    rt_confidence = models.IntegerField(default=None,null=True)
    feedback_given = models.BooleanField(default=False)
    block = models.CharField(max_length=100)
    trial_number = models.IntegerField(default=None)
    

class QuestionnaireQ(models.Model):
    """Model class for a questionnaire question

    Args:
        models (models.Model): Django model object class
    """
    session = models.ForeignKey(Session, on_delete=models.CASCADE, related_name='questionnaire_q')
    questionnaire_name = models.CharField(max_length=100)
    subscale = models.CharField(max_length=100,blank=True,null=True)
    possible_answers = models.JSONField(default=dict)
    question = models.CharField(max_length=1000)
    answer = models.IntegerField()
    questionnaire_question_number = models.IntegerField()

drone_recon/views.py
'''
Contains the primary python code for managing the webapp

By Warren Woodrich Pettine, M.D.
Last Updated: 2023-08-30
'''

import json
import urllib
import os, logging
from datetime import datetime
from user_agents import parse
from django.db.models import Avg, Count
from django.http import HttpResponseRedirect, HttpResponse, HttpRequest, JsonResponse
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.utils import timezone
from django.views.decorators.csrf import csrf_exempt
from django.forms import modelformset_factory
from django import forms
from django.views.decorators.cache import never_cache
from drone_recon.models import Subject, Session, Trial, QuestionnaireQ, Stimulus, Strategy
from drone_recon.global_variables import *
from drone_recon.functions import getStimulusURLs, tutorialParameters, confidenceParameters, \
    taskParameters, getPaymentToken, createWelcomeMessage, getProlificPaymentTokens
from drone_recon.forms import processSubstanceForm, processMentalHealthHistoryForm, RegistrationForm,\
    timezoneModelForm, makeSubstancesRadioForm, sleepModelForm, makeMentalHealthHistoryRadioAgeForm,\
    makeQuestionnaireFormSet, attentionCheckList, checkAttention, CombinedFormSet, makeConditionalFormSet,\
    makeMentalHealthConditionalDict, makeSubstancesConditionalDict, fixSubstanceConditionalForm
from drone_recon.global_variables import *

import logging

    
# Get an instance of a logger
logger = logging.getLogger('django')

        
def extractURLParameters(request):
    """Obtains key task variables from the URL parameters

    Args:
        request (request): Django request object

    Returns:
        external_session_ID, external_study_ID, external_ID, webapp_use
    """
    external_session_ID = request.GET.get("SESSION_ID")
    external_study_ID = request.GET.get("STUDY_ID")
    external_ID = request.GET.get("PROLIFIC_PID")
    webapp_use = request.GET.get('WEBAPP_USE')
    # If no webapp use specificed, go with the default
    if webapp_use is None:
        webapp_use = DEFAULT_WEBAPP_USE
    # Make sure the required variables are present
    if DEPLOYMENT and ((external_ID == '') or (external_ID is None) or (external_study_ID == '') or \
        (external_study_ID is None) or (external_session_ID == '') or (external_session_ID is None)):
        return fishy(request)
    if (external_session_ID == '') or (external_session_ID is None):
        external_session_ID = 'test'
    if (external_study_ID == '') or (external_study_ID is None):
        external_study_ID = 'foo'
    if (external_ID == '') or (external_ID is None):
        external_ID = 'bar'  
    return external_session_ID, external_study_ID, external_ID, webapp_use


def index(request):
    """Index page for the webapp. This is the first page that is loaded. This can be modified

    Args:
        request (request): Django request object

    Returns:
        view: A re-direct to the consent form. 
    """
    try:
        return consentform(request)
    except:
        logger.error(f'Something went wrong in the index function')


def health(request):
    """Determine the health of the webapp. This is used by Azure to determine if the webapp is running

    Args:
        request (request): Django request object

    Returns:
        HttpResponse() or error
    """
    try:
        return HttpResponse()
    except Exception as e:
        logger.error('Error in %s', 'consentformProlific', exc_info=e)
        

def consentform(request):
    """Consent form for the webapp. This is the first page that is loaded. 

    Args:
        request (request):

    Returns:
        view: direct to the appropriate consent form
    """
    if PROLIFIC:
        # Prolific pulls URL parameters, so we use a different consent form.
        return consentformProlific(request)
    else:
        # The standard one doesn't pull parameters from the URL
        return consentformStandard(request)
    
    
def consentformStandard(request):
    """Standard request form, used when not using Prolific. User enters many key variables

    Args:
        request (_type_): _description_

    Returns:
        render: renders the page
    """
    try:
        link_url = 'drone_recon:welcome'
        return render(request, "drone_recon/consentform.html", {
            "link_url": link_url,
        })
    except Exception as e:
        logger.error('Error in %s', 'consentformStandard', exc_info=e)


def consentformProlific(request):
    """Request form for Prolific, where key variables are extracted from the URL. 

    Args:
        request (_type_): _description_

    Returns:
        render: renders the page.
    """
    try:
        #Grab information from the URL parameters
        external_session_ID, external_study_ID, external_ID, webapp_use = extractURLParameters(request)
        request.session['external_session_ID'] = external_session_ID
        request.session['external_study_ID'] = external_study_ID
        request.session['external_ID'] = external_ID
        request.session['webapp_use'] = webapp_use
        #Tell it where to send users
        link_url = 'drone_recon:welcome'
        return render(request, "drone_recon/consentform.html", {
            "link_url": link_url,
        })
    except Exception as e:
        logger.error('Error in %s', 'consentformProlific', exc_info=e)
    
    
def welcome(request):
    """Welcomes the user, creates a new session and process initial input variables. 

    Args:
        request (_type_): _description_

    Returns:
        Either the initial welcome screen or a re-direct to the next view
    """
    logger.info('In welcome function')
    check_sustance_form = False
    try:
        # return render(request, "drone_recon/welcome.html")
        if request.method == "POST":
            # Check the reCAPTCHA
            recaptcha_valid = True            
            if not DEBUG:
                ''' Begin reCAPTCHA validation '''
                recaptcha_response = request.POST.get('g-recaptcha-response')
                url = 'https://www.google.com/recaptcha/api/siteverify'
                values = {
                    'secret': os.environ['GOOGLE_RECAPTCHA_SECRET_KEY'],
                    'response': recaptcha_response
                }
                data = urllib.parse.urlencode(values).encode()
                req = urllib.request.Request(url, data=data)
                response = urllib.request.urlopen(req)
                result = json.loads(response.read().decode())                
                ''' End reCAPTCHA validation '''
                if not result['success']:
                    recaptcha_valid = False
            if recaptcha_valid:
                # Check if a new user needs to be created
                if (not 'external_ID' in request.session) or(('external_ID' in request.session) and\
                        (not Subject.objects.filter(external_ID=request.session['external_ID']).exists())):
                    # Go through and process the form for a new user
                    form = RegistrationForm(request.POST)
                    if form.is_valid():
                        #Create variables to be entered
                        if PROLIFIC:
                            if DEPLOYMENT:
                                subject_source = 'prolific'
                            else:
                                subject_source = 'internal'
                            if 'external_session_ID' in request.session.keys():
                                external_session_ID = request.session['external_session_ID']
                                external_study_ID = request.session['external_study_ID']
                                user_ID = request.session['external_ID']
                            else:
                                #Grab information from the URL parameters
                                external_session_ID, external_study_ID, user_ID, _ = extractURLParameters(request)
                        else:
                            user_ID = form.cleaned_data["user_ID"]
                            subject_source = form.cleaned_data["subject_source"]
                            external_study_ID = 'foo'
                            external_session_ID = 'bar'
                        age = form.cleaned_data["age"]
                        gender = form.cleaned_data["gender"]
                        sex = form.cleaned_data["sex"]
                        education = form.cleaned_data["education"]
                        start_time = form.cleaned_data["start_time"]
                        #Check if subject exists, if not create them
                        if Subject.objects.filter(external_ID=user_ID,external_source=subject_source).exists():
                            if DEPLOYMENT:
                                return alreadyCompleted(request)
                            subject = Subject.objects.filter(external_ID=user_ID)[0]
                        else:
                            subject = Subject(external_ID=user_ID, gender=gender, sex=sex, age=age,
                                              education=education,external_source=subject_source)
                            subject.save()
                    else:
                        raise ValueError('Invalid Form')
                else: # The user exists, and we have their info from the URL
                    user_ID = request.session['external_ID']
                    external_study_ID = request.session['external_study_ID']
                    external_session_ID = request.session['external_session_ID']
                    subject = Subject.objects.filter(external_ID=user_ID)[0]
                    start_time = datetime.now()
                # Logic as to whether one checks the forms
                check_sustance_form = True
                check_sleep_form = True
                #Create a new Session
                # payment_token = getPaymentToken()

drone_recon/templates/drone_recon/alreadycompleted.html
{% extends "alienartifacts/layout.html" %}

{% block body %}
    <body>
    <div label="exit_message">
        It looks like you've done this task before. Thanks for the interest, but we need fresh subjects!
    </div>
    </body>
{% endblock %}

drone_recon/templates/drone_recon/attentionfailure.html
{% extends "drone_recon/layout.html" %}

{% block body %}
    <body>
    <div label="exit_message">
        Please use the following code at Prolific:
        <br>
        <br>
        {{ token }}
        <br>
        <br>
        You can close this window.
    </div>
    </body>
{% endblock %}

drone_recon/templates/drone_recon/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    {% block head %}
        <title>Django web app with PostgreSQL in Azure - {% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
        <link rel="stylesheet" href="{% static 'fontawesome/css/all.min.css' %}">
        <link rel="icon"href="{% static 'favicon.ico' %}">
    {% endblock %}
</head>
<body>
    <nav class="navbar navbar-expand-md navbar-light fixed-top bg-light">
        <div class="container">
          <a class="navbar-brand" href="/">
            <img src="{% static 'images/azure-icon.svg' %}" alt="" width="30" height="24" class="d-inline-block align-text-top">
            Azure Restaurant Review
          </a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarCollapse">                
            <ul class="navbar-nav mb-2 mb-md-0 ms-auto">
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="dropdown07XL" data-bs-toggle="dropdown" aria-expanded="true">Azure Docs</a>
                    <ul class="dropdown-menu" aria-labelledby="dropdown07XL" data-bs-popper="none">
                        <li><a class="dropdown-item" target="_blank" href="https://docs.microsoft.com/azure">Azure Docs Home</a></li>
                        <li><a class="dropdown-item" target="_blank" href="#">Python Web App + PostgreSQL Database Tutorial</a></li>
                        <li><a class="dropdown-item" target="_blank" href="https://azure.microsoft.com/develop/python/">Python on Azure</a></li>
                        <li><a class="dropdown-item" target="_blank" href="https://docs.microsoft.com/azure/developer/python">Python on Azure Developer Center</a></li>
                    </ul>
                </li>
            </ul>
          </div>
        </div>
      </nav>

      <main class="container">    
        {% block content %}{% endblock %}
      </main>
      <script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>      
</body>
</html>

drone_recon/templates/drone_recon/consentform.html
{% extends "drone_recon/layout.html" %}

{% block body %}

    <h1>Online Consent for Participation</h1>

    <p align="center">&nbsp;</p>
    <p align="center">YALE UNIVERSITY</p>
    <p align="center">&nbsp;YALE UNIVERSITY SCHOOL OF MEDICINE</p>
    <p align="center">DEPARTMENT OF PSYCHIATRY</p>
    <p align="center">&nbsp;</p>
    <p align="center">&nbsp;</p>
    <p align="center"><strong>Title</strong>: Latent State&nbsp;Reinforcement-Learning</p>
    <p align="center">&nbsp;</p>
    <p align="center"><strong>Principal Investigator:&nbsp;</strong>John Murray, Ph.D.,&nbsp;<a href="mailto:john.murray@yale.edu" style="font-size:inherit">john.murray@yale.edu</a></p>
    <p align="center"><strong>Contact:&nbsp;</strong>Warren Woodrich Pettine, M.D.,&nbsp;<a href="http://warren.pettine@yale.edu/" style="font-size:inherit">warren.pettine@yale.edu</a></p>
    <p>&nbsp;</p>
    <p><strong>Introduction</strong></p>
    <p>You are being asked to join a research study.&nbsp; The following information will explain the purpose of the study, what you will be asked to do, and the potential risks and benefits.</p>
    <p>&nbsp;</p>
    <p><strong>Purpose</strong></p>
    <p>The purpose of this study is to learn about cognitive strategies in the context of a rule-based reinforcement-learning task. You are being asked to participate because you are a Prolific or mTURK worker interested in this study. We are particularly interested in how psychiatric traits relate to cognitive strategies.</p>
    <p>&nbsp;</p>
    <p><strong>Procedures</strong></p>
    <p>If you choose to participate in the study, you will perform a rule-based reinforcement-learning task. You will be shown visual cues and you need to respond by pressing a key. Through trial and error, you will learn the correct key to press for a given stimulus. There is a tutorial and then several test blocks. You will also answer some questions about non-identifiable demographic information (e.g., gender, age, educational level), lifestyle (e.g., research familiarity), psychiatric history (e.g. formal diagnosis of autism), as well as questions from standard psychiatric questionnaires. You will earn $4&nbsp;for successfully completing the questionnaires and tutorial, as well as another $4&nbsp;for completing the task. You will earn up to $4&nbsp;bonus for responding accurately. This study should take less than 60 minutes to complete. We do not anticipate any risks during the study beyond those typically experienced on a day-to-day basis.&nbsp;</p>
    <p>&nbsp;</p>
    <p><strong>Possible Benefits</strong></p>
    <p>This research is not designed to benefit you directly. However, knowledge gained from the results may help us to better understand cognitive function, particularly those with psychiatric disorders.</p>
    <p>&nbsp;</p>
    <p><strong>Possible Risks</strong></p>
    <p>There is no physical or psychological risk in this study. There is a slight risk regarding the confidentiality of your participation in this study, if information about you becomes known to persons outside this study.&nbsp; The researchers are required to keep your study information confidential, however, so the risk of breach of confidentiality is very low.</p>
    <p>&nbsp;</p>
    <p><strong>Privacy / Confidentiality</strong></p>
    <p>We will not collect any identifying information such as your name. It is a possible that your work IDs is linked to your public profile. However, the worker IDs will only be collected for the purposes of distributing compensation. Furthermore, only the researchers involved in this study and those responsible for research oversight will have access to the worker IDs and other information you provide. The worker IDs will never be posted or published. Therefore, while your responses in the study are anonymous, your participation is confidential.&nbsp;</p>
    <p>&nbsp;</p>
    <p><strong>Voluntary Participation</strong></p>
    <p>Participation in this study is completely voluntary.&nbsp; You are free to decline to participate, and to end participation at any time for any reason. Refusing to participate will involve no penalty or loss of benefits to which you are otherwise entitled. By providing consent, you have not given up any of your legal rights.</p>
    <p>&nbsp;</p>
    <p><strong>Questions</strong></p>
    <p>You have read the above description of the research study, including the risks and benefits involved. At this point, if you have questions regarding the study that you would like to have answered before you begin, please email the Principal Investigator as described below.</p>
    <p>&nbsp;</p>
    <p>If you have any further questions about this study, you may contact the investigator, [Dr. Warren Woodrich Pettine,&nbsp;<a href="http://warren.pettine@yale.edu/" style="font-size:inherit">warren.pettine@yale.edu</a>]. If you would like to talk with someone other than the researchers to discuss problems, concerns, and questions you may have concerning this research, or to discuss your rights as a research subject, you may contact the Yale Human Investigation Committee at (203) 785-4688.</p>

    <a id="to-task" href="{% url link_url %}">Consent to join study</a>
{% endblock %}

drone_recon/templates/drone_recon/fishy.html
{% extends "drone_recon/layout.html" %}

{% block body %}
    <body>
    <div label="exit_message">
        Our algorithms detected that you're up to no good. 
    </div>
    </body>
{% endblock %}

drone_recon/templates/drone_recon/layout.html
<!DOCTYPE html>
{% load static %}

<html lang="en">


<head>
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
    <meta charset="UTF-8">
    <title>Drone Recon</title>
</head>
<body>

    {% block body %}
    {% endblock %}

</body>
</html>

drone_recon/templates/drone_recon/prohibitedbrowser.html
{% extends "drone_recon/layout.html" %}

{% block body %}
    <body>
    <div label="exit_message">
        Unfortunately, your using a web browser that does not enable functionality needed for this game (like requiring full screen). At present, the prohibited list includes:
        <br>
        <br>
        {% for item in prohibited_browsers %}
            <li>{{ item }}</li>
        {% endfor %}
        <br>
        <br>
        You can try the task again using a different browser. However, please make sure to open it from the full URL you were provided. We pay you using parameters from the URL. Thanks!
    </div>
    </body>
{% endblock %}

drone_recon/templates/drone_recon/questionnaires.html
{% extends "drone_recon/layout.html" %}

{% block content %}
{% block body %}
    {{ conditional_questions|json_script:"conditional_questions" }}
  <form action="{% url 'drone_recon:questionnaires' %}" method="post" class="pure-form pure-form-aligned form_style">
    {% csrf_token %}

      <h3> Please read through the questions carefully</h3>
        <em> ***questions referring to casual interaction with acquaintances, rather than special
        relationships such as with close friends and family members.</em>
        <br>

    <div id="radio-questions">
      {% for formset_ in formsets_combined.formsets %}
          {{ formset_.management_form }}
        {% for form in formset_ %}
          {{ form.as_p }}
        {% endfor %}
      {% endfor %}

      {{ form_att_check.as_p }}
    </div>

    <h3>Have you ever been formally diagnosed by a physician with the following conditions?</h3>
    <div id="radio-questions">
      {{ form_mh.as_p | safe}}
    </div>

    {% load static %}
    <script src="{% static 'js/conditionalforms.js' %}"></script>

    <button type="submit">Submit</button>
  </form>

{% endblock %}

{% endblock %}

drone_recon/templates/drone_recon/token.html
{% extends "drone_recon/layout.html" %}

{% block body %}

    
    <div id="token_message">
        {{ token_message|safe}}
    </div>


{% endblock %}

drone_recon/templates/drone_recon/welcome.html
{% extends "drone_recon/layout.html" %}

{% block body %}
    {{ conditional_questions|json_script:"conditional_questions" }}
    
    <h1>Welcome!</h1>

    <div>
        <p>
            <h3>{{ welcome_message }}</h3>
        </p>
    </div>

    <form action="{% url 'drone_recon:welcome' %}" method="post" class="pure-form pure-form-aligned">
        {% csrf_token %}
        
        {{ form_demographics.as_p }}
        {{ timezone_form }}
        {{ form_sleep.as_p }}

        <h3>{{ form_header_text }}</h3>
        <div id="radio-questions">
            {{ form_substances.as_p}}
        </div>

        {% if recaptcha.bool %}
            <div class="center_captcha">
            <script src={{ recaptcha.src }}></script>
            <div class="g-recaptcha" data-sitekey={{ recaptcha.site_key }}></div>
            </div>
        {% endif %}

        {% load static %}
        <script src="{% static 'js/conditionalforms.js' %}"></script>

        <input type="submit" name="Let's Go!">
    </form>


<script type="text/javascript">
    const timezone_id = "{{ timezone_form.timezone.auto_id }}";
    let timezone = new Date().toString().match(/([A-Z]+[\+-][0-9]+.*)/)[1];
    document.getElementById(timezone_id).value = timezone;
</script>

{% endblock %}